import ollama

auditor_prompt = """
You are the SYSTEM LOGIC AUDITOR (Level 2).
Your task is to review the YAML blueprint generated by the Analyst.

CHECKLIST:
1. Circular Dependencies: Modules should not create loops.
2. Inputs/Outputs: Each input must be provided by another module or defined in the glossary.
3. Filenames and class names: Classes in CamelCase, filenames in snake_case.
4. Each module must have a start() or run() method.
5. No non-existent external dependencies.
6. Clarity: Inputs and outputs must be specific and usable by a programmer.

RESPONSE RULE:
- If perfect, start with: "VERDICT: PASSED"
- If issues, start with: "VERDICT: FAILED" and list the reasons.
"""

def run_auditor():
    print("--- AGENT: LOGIC AUDITOR (L2) ---")

    try:
        with open("draft_plan.yaml", "r", encoding="utf-8") as f:
            blueprint = f.read()
    except FileNotFoundError:
        print("Error: draft_plan.yaml not found!")
        return

    print("[System] Auditing the blueprint for logic errors...\n")

    response = ollama.chat(model='llama3.1', messages=[
        {'role': 'system', 'content': auditor_prompt},
        {'role': 'user', 'content': f"Review this blueprint:\n\n{blueprint}"},
    ])

    verdict = response['message']['content']

    print("-" * 20 + " AUDIT REPORT " + "-" * 20)
    print(verdict)
    print("-" * 50)

    if "PASSED" in verdict:
        print(">> Logic verified. Ready for Module Architects.")
    else:
        print(">> Logic rejected. Improvements needed.")

if __name__ == "__main__":
    run_auditor()
