
# Environment & Model Configuration
MODEL_NAME = 'llama3.1'
MAX_RETRIES = 3

# File & Directory Paths
OUTPUT_DIR = "output"
METADATA_DIR_NAME = ".factory"
BLACKBOARD_FILE = "blackboard.json"
ORCHESTRATION_LOG_FILE = "orchestration_log.jsonl"
QUALITY_REMARKS_FILE = "quality_remarks.jsonl"
INTERACTION_DEBUG_FILE = "interaction_debug.txt"
CONSOLE_LOG_FILE = "console_log.txt"
REQUIREMENTS_FILE = "requirements.txt"
DEBUG_SNAPSHOTS_DIR = "debug_snapshots"
DEBUG_REPORT_FILE = "debug_report.md"
MAIN_SCRIPT_NAME = "main.py"
RUN_SCRIPT_NAME = "run_app.bat"
TESTS_DIR_NAME = "tests"
TEMPLATES_DIR_NAME = "templates"
STATIC_DIR_NAME = "static"

# Core Engineering Pipeline
AGENT_L1_ANALYST = "L1_ANALYST"
AGENT_L2_AUDITOR = "L2_AUDITOR"
AGENT_L3_ARCHITECT = "L3_ARCHITECT"
AGENT_L4_DEVELOPER = "L4_DEVELOPER"
AGENT_L45_REVIEWER = "L4_5_REVIEWER"
AGENT_L475_OPTIMIZER = "L4_75_OPTIMIZER"
AGENT_L5_INTEGRATOR = "L5_INTEGRATOR"
AGENT_L6_DEBUGGER = "L6_DEBUGGER"

# Specialist / Cross-Cutting Agents
AGENT_DEPENDENCY_AGENT = "DEPENDENCY_AGENT"
AGENT_TEST_ENGINEER = "TEST_ENGINEER"
AGENT_SECURITY_AGENT = "SECURITY_AGENT"
AGENT_FRONTEND_DEV = "FRONTEND_DEV"
AGENT_SYSTEM_AUDITOR = "SYSTEM_AUDITOR"

# Module Types
MODULE_TYPE_WEB = "web_interface"
MODULE_TYPE_SERVICE = "service"
MODULE_TYPE_UTILITY = "utility"

# Statuses
STATUS_INFO = "INFO"
STATUS_RUNNING = "RUNNING"
STATUS_SUCCESS = "SUCCESS"
STATUS_WARNING = "WARNING"
STATUS_ERROR = "ERROR"
STATUS_FAILED = "FAILED"
